import {
  abstract,
  apeChain,
  arcTestnet,
  arbitrum,
  arbitrumSepolia,
  avalanche,
  base,
  baseSepolia,
  berachain,
  blast,
  bob,
  boba,
  bsc,
  celo,
  corn,
  cronos,
  etherlink,
  flare,
  flowMainnet,
  fraxtal,
  fuse,
  gnosis,
  gravity,
  immutableZkEvm,
  ink,
  kaia,
  katana,
  linea,
  mainnet,
  mantle,
  megaeth,
  mode,
  monad,
  moonbeam,
  morph,
  opBNB,
  optimism,
  optimismSepolia,
  plasma,
  polygon,
  rootstock,
  ronin,
  scroll,
  sei,
  soneium,
  sonic,
  sophon,
  stable,
  superposition,
  swellchain,
  taiko,
  telos,
  unichain,
  vana,
  worldchain,
  xdc,
} from "viem/chains";
import { zeroAddress } from "viem";
import type { Chain } from "viem";
import { PluginConfig } from "./types.js";

export const NATIVE_TOKEN_ADDRESS = zeroAddress;


export const DEFAULT_CONFIG: PluginConfig = {
  lifiBaseUrl: "https://li.quest/v1",
  lifiApiKey: undefined,
  integrator: "openclaw-intent-transfer",
  defaultSlippageBps: 100,
  // Public RPC defaults are convenient for development but are typically rate-limited.
  rpcUrls: {
    ethereum: "https://cloudflare-eth.com/v1/mainnet",
    base: "https://mainnet.base.org",
    arbitrum: "https://arb1.arbitrum.io/rpc",
    optimism: "https://mainnet.optimism.io",
    polygon: "https://polygon.drpc.org"
  },
  minNativeReserve: {
    ethereum: "0.003",
    base: "0.002",
    arbitrum: "0.002",
    optimism: "0.002",
    polygon: "1"
  },
  routeStatusPollIntervalMs: 10_000,
  routeStatusTimeoutMs: 20 * 60 * 1000
};

export const LIFI_CHAIN_NAME_TO_VIEM_CHAIN: Record<string, Chain> = {
  abs: abstract,
  ape: apeChain,
  arct: arcTestnet,
  eth: mainnet,
  arb: arbitrum,
  arbs: arbitrumSepolia,
  ava: avalanche,
  bas: base,
  bast: baseSepolia,
  ber: berachain,
  bls: blast,
  bob: boba,
  boc: bob,
  bsc: bsc,
  cel: celo,
  crn: corn,
  cro: cronos,
  dai: gnosis,
  etl: etherlink,
  flr: flare,
  flw: flowMainnet,
  fra: fraxtal,
  fus: fuse,
  gra: gravity,
  imx: immutableZkEvm,
  ink: ink,
  kai: kaia,
  kat: katana,
  lna: linea,

  //lns: lens,
  //lsk: lisk,
  //mam: metis,
  //hyp: hyperEvm,
  //tem: tempo,
  //hmi: hemi,
  //hpl: hyperliquid,
  //plu: plume,
  //vic: viction,

  meg: megaeth,
  mnt: mantle,
  mod: mode,
  mon: monad,
  moo: moonbeam,
  mop: morph,
  opt: optimism,
  opst: optimismSepolia,
  opb: opBNB,
  pol: polygon,
  pla: plasma,
  ron: ronin,
  rsk: rootstock,
  scl: scroll,
  sei: sei,
  soe: soneium,
  son: sonic,
  sop: sophon,
  sta: stable,
  sup: superposition,
  swl: swellchain,
  tai: taiko,
  tlo: telos,
  uni: unichain,
  van: vana,
  wcc: worldchain,
  xdc: xdc
};
